### ISSUE TITLE
building without docker

### ISSUE THREAD

**Issue by johnroper100** [SpComb/qmsk-dmx#8]
Can you share how to build this without using docker? I know that docker is the recoomended way, but I can't use docker for the project I am working on.

**Comment by SpComb** [comment]
The contents of the Dockerfile itself is probably the best docs: https://github.com/qmsk/dmx/blob/master/Dockerfile

It's fairly straightforward, assuming that you have the necessary tools installed: `dep ensure` + `go install` for the backend, and `npm install` + `tsc` for the frontend.
